apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  db_host: 0.0.0.0
  db_password: postgres
  zipkin_reporter_uri: "http://0.0.0.0:9411/api/v2/spans"
  collect_from: "http://0.0.0.0:4000/debug/vars"
