kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Sales-Api
  - containerPort: 3000
    hostPort: 3000
  # Sales-Api debug
  - containerPort: 4000
    hostPort: 4000
  # Metrics
  - containerPort: 3001
    hostPort: 3001
  # Metrics debug
  - containerPort: 4001
    hostPort: 4001
  # Grafana
  - containerPort: 3100
    hostPort: 3100
  # Vault
  - containerPort: 8200
    hostPort: 8200
  # Postgres
  - containerPort: 5432
    hostPort: 5432
  # Prometheus
  - containerPort: 9090
    hostPort: 9090
  # Tempo (tracing)
  - containerPort: 9411
    hostPort: 9411

# If you want to use storge from local disk.
#
# Change this:
#
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane

# To this:
#
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane
#   extraMounts:
#     - hostPath: /home/bill/your/pg/directory/here
#       containerPath: /path/inside/the/kind/container
# 
# And, then, in the pod definition, do this:
# volumes:
#
# - name: data
#   hostPath:
#     path: /path/inside/the/kind/container
