# https://docs.docker.com/compose/compose-file
version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411

  # This starts a local PostgreSQL DB.
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432

    # This is the core CRUD based service.
  sales-api:
    container_name: sales-api
    networks:
      - shared-network
    image: gcr.io/${PROJECT}/sales-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    environment:
      - SALES_DB_DISABLE_TLS=1 # This is only disabled for our development enviroment.
      # - GODEBUG=gctrace=1
    depends_on:
      - zipkin
      - db

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: gcr.io/${PROJECT}/metrics-amd64:1.0
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API
    depends_on:
      - sales-api