apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.23
        ports:
        - name: zipkin
          containerPort: 9411
      - name: app
        image: sales-api-amd64:1.0
        env:
        - name: SALES_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        - name: SALES_ZIPKIN_REPORTER_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: zipkin_reporter_uri
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: app
          containerPort: 3000
        - name: app-debug
          containerPort: 4000
        readinessProbe:
          httpGet:
            path: /debug/readiness
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /debug/liveness
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 15
      - name: metrics
        image: metrics-amd64:1.0
        env:
        - name: METRICS_COLLECT_FROM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: collect_from
        ports:
        - name: metrics
          containerPort: 3001
        - name: metrics-debug
          containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
spec:
  selector:
    service: sales-api
  ports:
  - name: zipkin
    port: 9411
    targetPort: zipkin
  - name: app
    port: 3000
    targetPort: app
  - name: app-debug
    port: 4000
    targetPort: app-debug
  - name: metrics
    port: 3001
    targetPort: metrics
  - name: metrics-debug
    port: 4001
    targetPort: metrics-debug
