{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: sales-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sales.labels" . | nindent 4 }}
type: Opaque
stringData:
  db_password: {{ .Values.secret.password | quote }}
{{- end }}
