apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
# Service for Vault Server
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: sales-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  annotations:
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: http
      nodePort: 32000
    - name: https-internal
      port: 8201
      targetPort: https-internal
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
---
# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: vault-internal
  namespace: sales-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  annotations:
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: http
    - name: https-internal
      port: 8201
      targetPort: https-internal
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
