apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf-datasources
  namespace: sales-system
data:
  tempo.yaml: |
    apiVersion: 1
    
    deleteDatasources:
      - name: Tempo
        orgId: 1
    
    datasources:
      - name: Tempo
        type: tempo
        url: http://tempo.sales-system.svc:3200
        access: proxy
        isDefault: true
        jsonData:
          tracesToMetrics:
          datasourceUid: 'Prometheus'
          tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
          queries:
            - name: 'Sample query'
              query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
          serviceMap:
            datasourceUid: 'Prometheus'
          nodeGraph:
            enabled: true
          search:
            hide: false
          spanBar:
            type: 'Tag'
            tag: 'http.path'
        version: 1
        editable: true
      - name: Prometheus
        type: prometheus
        url: http://prometheus.sales-system.svc:9090
        access: proxy
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          prometheusVersion: 2.44.0
          nodeGraph:
            enabled: true
          search:
            hide: false
          spanBar:
            type: 'Tag'
            tag: 'http.path'
        version: 1
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf-dashboards
  namespace: sales-system
data:
  dashboards.yaml: |
    apiVersion: 1
    
    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 30
        options:
          path: /etc/dashboards
          foldersFromFilesStructure: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: sales-system
data:
  sales-api.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "description": "Sales API",
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "uid": "PBFA97CFB590B2093",
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "custom": {
                "drawStyle": "line",
                "lineInterpolation": "linear",
                "barAlignment": 0,
                "lineWidth": 1,
                "fillOpacity": 0,
                "gradientMode": "none",
                "spanNulls": false,
                "showPoints": "auto",
                "pointSize": 5,
                "stacking": {
                  "mode": "none",
                  "group": "A"
                },
                "axisPlacement": "auto",
                "axisLabel": "",
                "axisColorMode": "text",
                "scaleDistribution": {
                  "type": "linear"
                },
                "axisCenteredZero": false,
                "hideFrom": {
                  "tooltip": false,
                  "viz": false,
                  "legend": false
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "color": {
                "mode": "palette-classic"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "tooltip": {
              "mode": "single",
              "sort": "none"
            },
            "legend": {
              "showLegend": true,
              "displayMode": "list",
              "placement": "bottom",
              "calcs": []
            }
          },
          "targets": [
            {
              "datasource": {
                "uid": "PBFA97CFB590B2093",
                "type": "prometheus"
              },
              "refId": "A",
              "hide": false,
              "editorMode": "builder",
              "expr": "requests{job=\"sales-api\"}",
              "legendFormat": "__auto",
              "range": true
            },
            {
              "datasource": {
                "uid": "PBFA97CFB590B2093",
                "type": "prometheus"
              },
              "refId": "B",
              "hide": false,
              "editorMode": "builder",
              "expr": "errors{job=\"sales-api\"}",
              "legendFormat": "__auto",
              "range": true
            },
            {
              "datasource": {
                "uid": "PBFA97CFB590B2093",
                "type": "prometheus"
              },
              "refId": "C",
              "hide": false,
              "editorMode": "builder",
              "expr": "goroutines{job=\"sales-api\"}",
              "legendFormat": "__auto",
              "range": true
            },
            {
              "datasource": {
                "uid": "PBFA97CFB590B2093",
                "type": "prometheus"
              },
              "refId": "D",
              "hide": false,
              "editorMode": "builder",
              "expr": "panics{job=\"sales-api\"}",
              "legendFormat": "__auto",
              "range": true
            }
          ],
          "title": "Sales API - Metrics",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "tempo",
            "uid": "P214B5B846CF3925F"
          },
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 1,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true
          },
          "pluginVersion": "9.5.2",
          "targets": [
            {
              "datasource": {
                "type": "tempo",
                "uid": "P214B5B846CF3925F"
              },
              "key": "Q-9fc3b403-aa1a-4311-978b-cda05474ac3e-0",
              "limit": 20,
              "queryType": "nativeSearch",
              "refId": "A",
              "serviceName": "sales-api"
            }
          ],
          "title": "Sales API - Traces",
          "type": "table"
        }
      ],
      "refresh": "15s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Sales API",
      "uid": "ccad8cb7-1592-4328-b38b-b4226a5d00a6",
      "version": 1,
      "weekStart": ""
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: sales-system
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      namespace: sales-system
      labels:
        app: grafana
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: grafana
          image: grafana/grafana:9.5.2
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: 'false'
            - name: GF_ANALYTICS_CHECK_FOR_UPDATES
              value: 'false'
            - name: GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES
              value: 'false'
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: 'traceqlEditor'
            - name: GF_SERVER_HTTP_PORT
              value: '3100'
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: 'Admin'
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/etc/dashboards/sales-api.json"
          ports:
            - containerPort: 3100
              name: http-grafana
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: http-grafana
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http-grafana
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: config-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: config-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /etc/dashboards
      volumes:
        - name: config-datasources
          configMap:
            name: grafana-conf-datasources
        - name: config-dashboards
          configMap:
            name: grafana-conf-dashboards
        - name: dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http-grafana
      port: 3100
      targetPort: http-grafana
