apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  selector:
    matchLabels:
      app: sales-api
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.11
        ports:
        - name: zipkin
          containerPort: 9411
        resources: {}
      - name: sales-api
        image: gcr.io/ardan-starter-kit/sales-api-amd64:1.0
        env:
        - name: SALES_AUTH_PRIVATE_KEY_FILE
          value: "/app/private.pem"
        - name: SALES_DB_HOST
          value: 0.0.0.0
        - name: SALES_DB_DISABLE_TLS
          value: "true"
        - name: SALES_Zipkin_Reporter_URI
          value: http://0.0.0.0:9411/api/v2/spans
        ports:
        - name: sales-api
          containerPort: 3000
        - name: debug
          containerPort: 4000
        resources: {}
      - name: metrics
        image: gcr.io/ardan-starter-kit/metrics-amd64:1.0
        env:
        - name: METRICS_COLLECT_FROM
          value: "http://localhost:4000/debug/vars"
        ports:
        - name: metrics
          containerPort: 3001
        - name: debug
          containerPort: 4001
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
spec:
  selector:
    service: sales-api
  ports:
  - name: "zipkin"
    port: 9411
    targetPort: 9411
  - name: "sales-api"
    port: 3000
    targetPort: 3000
  - name: "sales-api-debug"
    port: 4000
    targetPort: 4000
  - name: "metrics"
    port: 3001
    targetPort: 3001
  - name: "metrics-debug"
    port: 4001
    targetPort: 4001
