{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  db_password: {{ .Values.secret.password | quote }}
{{- end }}
