apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "auth.selectorLabels" . | nindent 4 }}
  ports:
    - name: auth
      port: {{ .Values.service.ports.http }}
      targetPort: auth
    - name: auth-debug
      port: {{ .Values.service.ports.debug }}
      targetPort: auth-debug
