apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kind-sales-config.yaml
- ../../base/sales-pod/
- ./kind-sales-quotas.yaml
patchesStrategicMerge:
- ./kind-sales-patch.yaml
images:
- name: metrics-image
  newName: metrics-amd64
  newTag: "1.0"
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
- name: sales-api-image
  newName: sales-api-amd64
  newTag: "1.0"
